version: "3.8"
services:
  postgres:
    container_name: devicemon_postgres
    image: postgres:14-bullseye
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - devicemon_postgres:/data/postgres
    ports:
      - ${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}
    networks:
      - devicemon
    restart: unless-stopped
  backend:
    image: ghcr.io/andreasbehnke/devicemon_backend:latest
    depends_on: [postgres]
    environment:
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-changeme}
      DATABASE_HOST: "devicemon_postgres"
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      MQTT_USER: ${MQTT_USER:-mqtt}
      MQTT_PASSWORD: ${MQTT_PASSWORD:-changeme}
      MQTT_PROTOCOL: ${MQTT_PROTOCOL:-tcp}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT:-1883}
    networks:
      - devicemon
  webclient:
    image: ghcr.io/andreasbehnke/devicemon_webclient:latest
    depends_on: [backend]
    ports:
      - "80:80"
      - "443:443"
    networks:
      - devicemon

networks:
  devicemon:
    driver: bridge

volumes:
  devicemon_postgres:
    name: "devicemon_prod_postgres"
