version: '3.5'

services:
  postgres:
    container_name: devicemon_dev_postgres
    image: postgres:16-bookworm
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - devicemon_dev_postgres:/data/postgres
    ports:
      - "127.0.0.1:${DATABASE_PORT:-5432}:5432"
    networks:
      - devicemon_dev_postgres
    restart: unless-stopped

  pgadmin:
    container_name: devicemon_dev_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - devicemon_dev_pgadmin:/root/.pgadmin

    ports:
      - "127.0.0.1:${PGADMIN_PORT:-8090}:80"
    networks:
      - devicemon_dev_postgres
    restart: unless-stopped

networks:
  devicemon_dev_postgres:
    driver: bridge

volumes:
  devicemon_dev_postgres:
    name: "devicemon_dev_postgres"
  devicemon_dev_pgadmin:
    name: "devicemon_dev_pgadmin_auth_jwt"
